// AUTO-GENERATED by scripts/i18n-translate-content.mjs — do not edit by hand.
// Maps locale code → flat content overlay ({ "id:field": "translated" }).
import ar from "./ar.json";
import de from "./de.json";
import el from "./el.json";
import es from "./es.json";
import fa from "./fa.json";
import fr from "./fr.json";
import ja from "./ja.json";
import ko from "./ko.json";
import pl from "./pl.json";
import pt from "./pt.json";
import ru from "./ru.json";
import sv from "./sv.json";
import tr from "./tr.json";
import uk from "./uk.json";
import zh from "./zh.json";

export const overlays: Record<string, Record<string, string>> = { ar, de, el, es, fa, fr, ja, ko, pl, pt, ru, sv, tr, uk, zh };
